#!/bin/bash
echo "Deploying..."

mkdir -p ~/.ssh
chmod 0700 ~/.ssh
ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
rsync -r --rsync-path='rsync' --delete-after --quiet --filter=':- .gitignore' ./src/ ${SSH_USER}@${SSH_HOST}:${REPO_PATH}

echo "Deploying finished."